{
 "title": "First-dashboard",
 "time": { "from": "2021-12-25T05:28:56.453Z", "to": "2022-04-23T00:47:28.389Z" },
 "panels": [
  {
   "title": "Prediction drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", prediction_drift AS \"value\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share mission values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", share_missing_values AS \"value\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Num drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", num_drifted_columns AS \"value\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", prediction_drift AS \"value\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}